export const medidores = {
  agua: [
    {
      instrumento: "Contadores de Agua de Chorro Único",
      precision: 7,
      precio: 8,
      garantia: 6,
      facilidadObtencion: 6,
      certificado: 7,
      tecnologia: 5,
      ponderado: 39,
    },
    {
      instrumento: "Contadores de Agua de Chorro múltiple",
      precision: 5,
      precio: 4,
      garantia: 7,
      facilidadObtencion: 6,
      certificado: 5,
      tecnologia: 5,
      ponderado: 32,
    },
    {
      instrumento: "Contador de agua tangencial",
      precision: 4,
      precio: 2,
      garantia: 8,
      facilidadObtencion: 5,
      certificado: 8,
      tecnologia: 5,
      ponderado: 27,
    },
    {
      instrumento: "Contador de Agua Woltmann",
      precision: 5,
      precio: 3,
      garantia: 5,
      facilidadObtencion: 4,
      certificado: 6,
      tecnologia: 7,
      ponderado: 30,
    },
    {
      instrumento: "Contador de Agua De Pistón Rotativo y Disco Oscilante",
      precision: 7,
      precio: 5,
      garantia: 7,
      facilidadObtencion: 6,
      certificado: 7,
      tecnologia: 5,
      ponderado: 38,
    },
    {
      instrumento: "Contador de Agua Electromagnético",
      precision: 5,
      precio: 4,
      garantia: 5,
      facilidadObtencion: 5,
      certificado: 6,
      tecnologia: 8,
      ponderado: 33,
    },
    {
      instrumento: "Contador de Agua ultrasónico",
      precision: 5,
      precio: 4,
      garantia: 5,
      facilidadObtencion: 5,
      certificado: 7,
      tecnologia: 8,
      ponderado: 34,
    },
    {
      instrumento: "Contador de Agua de desplazamiento Positivo y medidores de Velocidad",
      precision: 7,
      precio: 6,
      garantia: 7,
      facilidadObtencion: 6,
      certificado: 7,
      tecnologia: 5,
      ponderado: 37,
    },
    {
      instrumento: "Contador de agua de pistón oscilante y discos Nutantes",
      precision: 6,
      precio: 4,
      garantia: 7,
      facilidadObtencion: 6,
      certificado: 7,
      tecnologia: 5,
      ponderado: 35,
    },
  ],
  electricidad: [
    {
      instrumento: "Medidor monofásico",
      precision: 8,
      precio: 6,
      garantia: 8,
      facilidadObtencion: 9,
      certificado: 7,
      tecnologia: 4,
      ponderado: 42,
    },
    {
      instrumento: "Medidor trifásico",
      precision: 8,
      precio: 5,
      garantia: 8,
      facilidadObtencion: 8,
      certificado: 7,
      tecnologia: 4,
      ponderado: 40,
    },
    {
      instrumento: "Medidor Tiempo de uso",
      precision: 8,
      precio: 7,
      garantia: 6,
      facilidadObtencion: 7,
      certificado: 7,
      tecnologia: 4,
      ponderado: 38,
    },
    {
      instrumento: "Medidor inteligente",
      precision: 8,
      precio: 3,
      garantia: 8,
      facilidadObtencion: 2,
      certificado: 7,
      tecnologia: 6,
      ponderado: 39,
    },
    {
      instrumento: "Medidor de panel",
      precision: 8,
      precio: 2,
      garantia: 8,
      facilidadObtencion: 3,
      certificado: 7,
      tecnologia: 6,
      ponderado: 34,
    },
  ],
  gas: [
    {
      instrumento: "Contador para gas tipo diafragma",
      precision: 8,
      precio: 2,
      garantia: 7,
      facilidadObtencion: 8,
      certificado: 9,
      tecnologia: 4,
      ponderado: 34,
    },
    {
      instrumento: "Contador de gas ultrasónico",
      precision: 8,
      precio: 6,
      garantia: 7,
      facilidadObtencion: 6,
      certificado: 9,
      tecnologia: 8,
      ponderado: 42,
    },
    {
      instrumento: "Contador de turbina",
      precision: 7,
      precio: 5,
      garantia: 7,
      facilidadObtencion: 7,
      certificado: 9,
      tecnologia: 5,
      ponderado: 40,
    },
    {
      instrumento: "Contador de orificio",
      precision: 5,
      precio: 8,
      garantia: 6,
      facilidadObtencion: 8,
      certificado: 7,
      tecnologia: 4,
      ponderado: 38,
    },
    {
      instrumento: "Contador de coriolis",
      precision: 7,
      precio: 8,
      garantia: 6,
      facilidadObtencion: 6,
      certificado: 7,
      tecnologia: 5,
      ponderado: 39,
    },
    {
      instrumento: "Contador de flujo másico",
      precision: 8,
      precio: 6,
      garantia: 7,
      facilidadObtencion: 9,
      certificado: 9,
      tecnologia: 5,
      ponderado: 44,
    },
    {
      instrumento: "Contador rotativo",
      precision: 7,
      precio: 4,
      garantia: 7,
      facilidadObtencion: 6,
      certificado: 6,
      tecnologia: 7,
      ponderado: 37,
    },
  ],
};
